#!/bin/bash

which pacman >/dev/null 2>&1 || exit 1

function Setup::Package.update() {
    sudo pacman -Sy
}

function Setup::Package.install() {
    local package_name=$1
    sudo pacman -S --needed --noconfirm $1
}

################################################################################

Setup::Package.update
Setup::Package.install git
Setup::Package.install givm
Setup::Package.install zsh
Setup::Package.install tmux
Setup::Package.install apache
Setup::Package.install php
Setup::Package.install php-apache
Setup::Package.install php-intl
Setup::Package.install php-mcrypt
Setup::Package.install mariadb
Setup::Package.install phpmyadmin
